In [2]:
# importing pandas
import pandas as pd

pd.__version__

'2.2.2'

Loading the data

In [3]:
#loading the data from the csv file to a data frame 
df=pd.read_csv('data.csv')

Exploring data

In [4]:
#exploring data 

#displays first 5 rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [5]:
#display last 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [6]:
#random rows from the dataset 
df.sample(5)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
171,13387582,Wish Karo,Girls Black Polka Dot Printed Fit and Flare Dress,4.7,18,2123,65.0,"""₹743.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kot███da ███est█████████Ltd███,"[{""size"":""0-3M"",""value"":""18.6in"",""value_name"":...",NaN,"LL ███3, ███den█████████adu███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
482,18932802,DailyObjects,Blue & Pink Royal Parade Printed iPhone 12 Pro...,0.0,0,2199,68.0,"""₹703.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Fir███Who███ale█████████Lim██████,"[{""size"":""Onesize""}]",NaN,"Plo███o. ███1, █████████foc███████████████████...","[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",mobile-accessories
391,18675392,Jack & Jones,Men Blue Skinny Fit Mildly Distressed Heavy Fa...,3.8,81,3499,50.0,"""₹1,749.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":16,""2_stars"":5,""3_stars"":3,""4_stars""...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",BES███NIT███IND█████████TS █████████,"[{""size"":""28/30"",""value"":""28.0in"",""value_name""...",NaN,"Lal███Res███ncy█████████or,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
791,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [7]:
# no of rows and columns in the data set
df.shape

(1000, 24)

In [8]:
#structural summary of the data 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [9]:
#statistical summary of the data 
# mean,mediam,standard deviation,min,max and Quartiles
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [10]:
#categorical columns summary
# top frequent values, unique values and also counts 
df.describe(include='object')

,title,product_description,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,427,699,1000,219,699,438,1000,1000,1000
unique,454,989,466,1,1000,16,998,658,967,808,302,301,672,219,298,22,468,159,97
top,Roadster,Women Pink Solid Top,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""A pair of navy blue running sp...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Blouse"",""specification...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops
freq,30,3,25,1000,1,650,2,16,4,114,27,40,135,1,40,126,306,265,122

In [11]:
#columns from the dataset
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [12]:
#data type of each column from the dataset
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

Handling Missing Values

In [13]:
#handling missing values
#missing values in each column
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [14]:
'''
the columns having null values are discount,what_customers_said, 
seller_name,videos ,seller_information and variantions
%of missing values of discount =12.1%
%of missing values of what_customers_said= 57.3%
%of missing values of seller_name=30.1%
%of missing values of videos=78.1%
%of missing values of seller_infomation=30.1%
%of missing values of variations=56.2
 '''

#filling null data
#filling discount with median
df["discount"] = df["discount"].fillna(df["discount"].median())

In [15]:
#seller_columns non null values
print(df["seller_name"].sample(10))

394                                           NaN
843                                           NaN
188    PRE███RE ███AIL█████████PRI███████████████
719                         Fla███tar███mme██████
249                         Vas███may███t. ██████
99           REL███CE ███U K█████████ATE█████████
955                            MAI███ KN███EAR███
854                                           NaN
306                     V P███WAL███SIE█████████Y
780                                           NaN
Name: seller_name, dtype: object

In [16]:
#handling missing value of seller_name
df["seller_name"] = df["seller_name"].fillna("Unknown Seller")

In [17]:
#displaying seller_information column
print(df["seller_information"].sample(10))

66     Pum███por███Ind█████████d/ ███████████████████...
354    172███REE███AGA█████████NA,███████████████████...
929    406███ 41███SAN█████████ILE███████████████████...
25     sec███ A-███Plo█████████, I███████████████████...
230    Sho███0 D███Mar█████████t E███████████████████...
220    117███IND███RIA█████████ II███████████████████...
824    Gro███ Fl███, N█████████old███████████████████...
852                                                  NaN
848                                                  NaN
696                                                  NaN
Name: seller_information, dtype: object

In [19]:
#handling missing values for seller_information
df["seller_information"] = df["seller_information"].fillna("Information not Found")

In [20]:
#display sample data of what_customer_said column
print(df['what_customers_said'].dtype) #object

#example data 
print(df[df["what_customers_said"].notna()]["what_customers_said"])

object
23     [{"percentage":"100","value_name":"Fit, Just R...
42     [{"percentage":"100","value_name":"Fit, Just R...
46     [{"percentage":"40","value_name":"Fit, A Littl...
48     [{"percentage":"100","value_name":"Fit, Just R...
51     [{"percentage":"70","value_name":"Fit, Just Ri...
                             ...
966    [{"percentage":"96","value_name":"Fit, Just Ri...
968    [{"percentage":"100","value_name":"Fit, A Litt...
969    [{"percentage":"50","value_name":"Fit, Just Ri...
970    [{"percentage":"67","value_name":"Fit, Just Ri...
971    [{"percentage":"67","value_name":"Fit, Just Ri...
Name: what_customers_said, Length: 427, dtype: object

In [21]:
#despite having 50%+ null values as we cannot ignore the feedback from the customers as they are 
#core business logic 
#handling the null values by adding an indicator flag (feature engineering !!)

#creating a indicator column as has_customer_reviews
df["has_customer_reviews"]=df['what_customers_said'].notna().astype(int)

#filling the null values with an empty list to preserve sturcture
df["what_customers_said"] = df["what_customers_said"].fillna("[]")

# Verify
print(df["what_customers_said"].isnull().sum())

#view the result
df[['what_customers_said', 'has_customer_reviews']].sample(10)

0

                                   what_customers_said  has_customer_reviews
186                                                 []                     0
0                                                   []                     0
785                                                 []                     0
818  [{"percentage":"100","value_name":"Fit, Just R...                     1
954  [{"percentage":"100","value_name":"Fit, Just R...                     1
52   [{"percentage":"100","value_name":"Fit, Just R...                     1
297  [{"percentage":"100","value_name":"Fit, Just R...                     1
902  [{"percentage":"67","value_name":"Fit, Just Ri...                     1
258                                                 []                     0
292                                                 []                     0

In [22]:
#sample data of vide0s and variations column which are not null
print(df["videos"].sample(10))

846                       NaN
29                        NaN
174                       NaN
110                       NaN
896                       NaN
388                       NaN
285                       NaN
99                        NaN
282                       NaN
755    ["rw-18240570_cae700"]
Name: videos, dtype: object

In [23]:
#dropping videos column as doesnt effect the actual analysis of the data
df=df.drop(columns=["videos"])

#verification 
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'has_customer_reviews'],
      dtype='object')

In [24]:
#sample data of variations column
print(df["variations"].sample(10))

877                                   NaN
152                         [{},{},{},{}]
69                                   [{}]
924                               [{},{}]
299                               [{},{}]
654    [{},{},{},{},{},{},{},{},{},{},{}]
115                                   NaN
856                                   NaN
445             [{},{},{},{},{},{},{},{}]
961                                   NaN
Name: variations, dtype: object

In [25]:
#dropping the variations column as there is no valid data
df=df.drop(columns=["variations"])

print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'best_offer',
       'more_offers', 'category', 'has_customer_reviews'],
      dtype='object')

In [26]:
df.isnull().sum()
#all null values have been handled

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
seller_information        0
best_offer                0
more_offers               0
category                  0
has_customer_reviews      0
dtype: int64

In [27]:
print(df['final_price'].dtype)
#final_price should be float value rather than a integer 
print(df["final_price"].sample(10))

object
462    "₹3,999.00"
365    "₹2,649.00"
554      "₹507.00"
903    "₹1,049.00"
346    "₹1,424.00"
713    "₹4,999.00"
355    "₹2,999.00"
727    "₹2,474.00"
580      "₹864.00"
789      "₹699.00"
Name: final_price, dtype: object

In [28]:
#converting final_price from object to float

#removing ruppe and comma symbol
df['final_price'] = df['final_price'].astype(str).str.replace(r'[^\d.]', '', regex=True)

#converting the object value to float value
df['final_price'] = pd.to_numeric(df['final_price'],errors='coerce')

print(df["final_price"].dtype)

print(df["final_price"].sample(10))

float64
313    1039.0
159    1799.0
815    1800.0
286     554.0
809     499.0
368    2749.0
487    1499.0
717    3599.0
428    1633.0
168    1899.0
Name: final_price, dtype: float64

Basic Operations

In [29]:
#selecting columns relevent for pricing analysis
pricing_df = df[['title', 'category', 'initial_price', 'final_price']]
pricing_df.head()

            title   category  initial_price  final_price
0     Lino Perros  backpacks           3995       3995.0
1  Tommy Hilfiger  backpacks           2899       2899.0
2           Lavie  backpacks           2999       2999.0
3          F Gear  backpacks           1675       1675.0
4       MYTRIDENT  bath-robe           2899       2899.0

In [30]:
#filtering items to show from backpack category
backpacks_only = df[df['category'] == 'backpacks']
print(f"Number of backpacks: {backpacks_only.shape[0]}")

Number of backpacks: 4

In [31]:
#filtering for products with rating higher than 4
highly_rated = df[df['rating'] > 4.5]
highly_rated.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category,has_customer_reviews
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Information not Found,{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,0
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,2999.0,INR,http://assets.myntassets.com/assets/images/186...,...,"[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Unknown Seller,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",Information not Found,{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,0
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.0,3839.0,INR,http://assets.myntassets.com/assets/images/214...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",SAI███USE███OT █████████ NA███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots,0
32,18656766,VStar,Beige Solid T-Shirt Bra,4.6,5,345,56.0,345.0,INR,http://assets.myntassets.com/assets/images/186...,...,"[{""specification_name"":""Back"",""specification_v...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],V S███ CR███ION█████████,"[{""size"":""30B"",""value"":""31.5in"",""value_name"":""...",VI/███ AB███ ST█████████ODE███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra,0
38,21873792,KARATCART,Cubic Zirconia Silver-Plated Wraparound Bracelet,4.6,5,3397,76.0,815.0,INR,http://assets.myntassets.com/assets/images/218...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",[],KOK███V G███AL █████████,"[{""size"":""Onesize"",""value"":""8.26in"",""value_nam...",Sho███58-███Sec█████████ain███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet,0

In [32]:
#products with high discount
great_deals= df[(df['discount'] > 60.0)]
great_deals.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category,has_customer_reviews
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",[],Unknown Seller,"[{""size"":""S""}]",Information not Found,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,1399.0,INR,http://assets.myntassets.com/assets/images/198...,...,"[{""specification_name"":""Fabric"",""specification...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",[],Unknown Seller,"[{""size"":""Onesize""}]",Information not Found,{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels,0
11,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329,74.0,865.0,INR,http://assets.myntassets.com/assets/images/183...,...,"[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Sig███Ove███as,"[{""size"":""Super King""}]",Old███. 2███162█████████o. ███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets,0
12,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499,73.0,404.0,INR,http://assets.myntassets.com/assets/images/183...,...,"[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",E-1███103███PIP█████████ IN███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets,0
13,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499,65.0,3499.0,INR,http://assets.myntassets.com/assets/images/184...,...,"[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",[],Unknown Seller,"[{""size"":""Double King""}]",Information not Found,{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,0

In [33]:
#title and discount for all products where discount greater than 50%
high_discount_titles = df.loc[df['discount'] > 50.0, ['title', 'discount']]
high_discount_titles.head()

         title  discount
0  Lino Perros      58.0
2        Lavie      65.0
3       F Gear      52.0
5          H&M      56.0
6   AVI Living      65.0

In [34]:
# Sort by rating descending
df.sort_values('rating', ascending=False).head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category,has_customer_reviews
658,14561272,ASICS,Court M 7In Men Black Solid Mid-Rise Tennis ...,5.0,5,2299,50.0,1149.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Spo███ IQ███,"[{""size"":""27"",""value"":""27.0in"",""value_name"":""T...",180███ Bh███ Wa█████████ Co███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,0
437,22110424,VASTRADO,Ethnic Motifs Printed Mandarin Collar Pure Cot...,5.0,2,1199,55.0,539.0,INR,http://assets.myntassets.com/assets/images/221...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],CRE███VE ███MEN█████████E L█████████,"[{""size"":""XS"",""value"":""40.2in"",""value_name"":""C...",G11███11-███-11█████████-11███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",kurtas,0
178,13449506,DOOR74,Women Black Solid Maxi Dress,5.0,7,2399,70.0,719.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],JXP███S,"[{""size"":""S"",""value"":""7.0in"",""value_name"":""Sle...",D74███D F███ANE█████████Noi███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,0
721,16864474,Puma,Men Orange & White Spike 22.2 Cricket Shoes,5.0,3,6999,20.0,5599.0,INR,http://assets.myntassets.com/assets/images/168...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Pum███por███Ind█████████td.█████████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",Pum███por███Ind█████████d/ ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes,0
88,16185546,ellementry,Gold-Toned 2 Pieces Stainless Steel Matte Spoon,5.0,5,1750,56.0,1750.0,INR,http://assets.myntassets.com/assets/images/161...,...,"[{""specification_name"":""Material"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Dil███ Es███tia█████████d,"[{""size"":""Onesize""}]",Vil███e C███ota█████████ayr███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",cutlery,0
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.0,3839.0,INR,http://assets.myntassets.com/assets/images/214...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",SAI███USE███OT █████████ NA███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots,0
917,18537496,Bannos Swagger,Women Grey Solid Joggers,5.0,5,1699,76.0,1699.0,INR,http://assets.myntassets.com/assets/images/185...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Unknown Seller,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...",Information not Found,{},"[{""offer_name"":""10% Instant Discount on Citi C...",track-pants,0
52,22436508,Bruchi CLUB,Men Low-Rise Anti-Bacterial Basic Briefs,5.0,4,888,65.0,310.0,INR,http://assets.myntassets.com/assets/images/224...,...,"[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BRU███ CL███APP█████████ATE█████████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",A-2███NOI███SEC█████████AUT███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs,1
881,9557519,MANGO,Women Yellow Self Design Top,5.0,1,2490,35.0,2490.0,INR,http://assets.myntassets.com/assets/images/955...,...,"[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""M"",""value"":""36.0in"",""value_name"":""To...",Information not Found,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops,1
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",[],Unknown Seller,"[{""size"":""Onesize""}]",Information not Found,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,0

In [35]:
# Value counts for category
df['category'].value_counts()

category
tops                  122
dresses               100
shirts                 97
jeans                  57
sports-shoes           51
                     ...
lounge-pants            1
lounge-shorts           1
mangalsutra             1
mobile-accessories      1
yoga-mats               1
Name: count, Length: 97, dtype: int64

Handling Duplicates

In [36]:
#total number of duplicates
df.duplicated().sum()

#checking for duplicate products Ids
print(df.duplicated(subset='product_id').sum())

0

Found 0 duplicates rows

Creating a dervied column as total_price

In [37]:
# as there is no quantity column in the dataset assuming the quantity=1
df['quantity']=1

#deriving total_amount column where 
#total_amount=final_price*quantity

df["total_amount"]=df["final_price"]*df["quantity"]

df.sample(5)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category,has_customer_reviews,quantity,total_amount
614,22326558,Dennis Lingo,Spread Collar Slim Fit Tartan Checked Pure Cot...,3.3,26,2499,76.0,599.0,INR,http://assets.myntassets.com/assets/images/223...,...,"[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Men███Bra███Tec█████████ Pr███████████████,"[{""size"":""38"",""value"":""39.0in"",""value_name"":""C...",2nd███oor███O. █████████Lan███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,1,1,599.0
909,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578,60.0,631.0,INR,http://assets.myntassets.com/assets/images/192...,...,"[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...","Fla███o 6███jay█████████s, ███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops,1,1,631.0
124,17586858,RARE,Women Orange Georgette A-Line Midi Dress,3.4,23,1799,55.0,809.0,INR,http://assets.myntassets.com/assets/images/175...,...,"[{""percentage"":""34"",""value_name"":""Fit, Just Ri...",EPI███RAN███PVT██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",EPI███RAN███PVT█████████ FI███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,1,1,809.0
517,18949542,Red Chief,Men Tan & Black Leather Comfort Sandals,4.3,32,3099,50.0,1549.0,INR,http://assets.myntassets.com/assets/images/189...,...,[],Lea███ Gl███l P█████████,"[{""size"":""6"",""value"":""26.63cm"",""value_name"":""T...","119███20,███1, █████████ND ███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sandals,0,1,1549.0
359,14991614,Roadster,Men Green Brand Logo Detail Tailored Jacket,4.2,363,1699,50.0,509.0,INR,http://assets.myntassets.com/assets/images/149...,...,"[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",GAR███CRY███S L█████████,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""C...","123███, K███ANW█████████hne█████████████████████","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,1,1,509.0

Saving the Cleaned dataset

In [38]:
#saving the cleaned dataset to a new csv file
df.to_csv("cleaned_data.csv",index=False)

In [39]:
#verifying the size
df.shape

(1000, 25)

In [40]:
#verifying the cleaned dataset
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'best_offer',
       'more_offers', 'category', 'has_customer_reviews', 'quantity',
       'total_amount'],
      dtype='object')