In [77]:
# importing pandas
import pandas as pd

pd.__version__

'2.2.2'

Loading the data

In [78]:
#loading the data from the csv file to a data frame 
df=pd.read_csv('data.csv')

Exploring data

In [79]:
#exploring data 

#displays first 5 rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [80]:
#display last 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [81]:
#random rows from the dataset 
df.sample(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
663,18942852,FITINC,Women Blue Skinny Fit High-Rise Training or Gy...,4.4,14,999,55.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Fit███ Ap███els█████████Lim██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,"GRO███ FL███, K█████████2, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
757,18337610,Roadster,Men Navy Blue Self-Striped Cardigan,4.3,32,2299,67.0,"""₹758.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""S"",""value"":""37.0in"",""value_name"":""Ch...","[""rw-18337610_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
203,22585502,Nimidiya,Ethnic Motifs Printed Dupatta,0.0,0,999,60.0,"""₹399.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,PRE███TI ███LEC██████,"[{""size"":""Onesize""}]",NaN,"10,███rac███ ro█████████ GU███████████████","[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dupatta
150,21242962,Tommy Hilfiger,Sustainable Pure Cotton Denim Shirt Dress With...,4.4,9,5999,40.0,"""₹5,699.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Fla███ech███tai███,"[{""size"":""XXS"",""value"":""30.5in"",""value_name"":""...","[""rw-21242962_cae700""]","3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
634,13722850,Roadster,X Discovery Adventures Women Olive Green Opaqu...,4.4,39,1999,50.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":6,""4_stars"":...",NaN,Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...",NaN,1 s███loo███Cab█████████-01███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
471,14325388,Anouk,Women Peach-Coloured Pure Cotton Ethnic Motifs...,4.1,99,2899,NaN,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/143...,...,"{""1_star"":9,""2_stars"":3,""3_stars"":10,""4_stars""...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""rw-14325388_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",kurta-sets
776,18830500,White Snow,Girls Beige Heart Printed Hooded Sweatshirt,4.2,10,1599,60.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""3-4Y"",""value"":""27.0in"",""value_name"":...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweatshirts
750,14280286,Harvard,Men Grey Melange Acrylic Chevron Pattern Pullover,3.3,54,1999,NaN,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/142...,...,"{""1_star"":16,""2_stars"":1,""3_stars"":10,""4_stars...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...","[""rw-14280286_cae700"",""https://videos.myntasse...",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweaters
536,16287694,Saree mall,Brown Floral Linen Blend Banarasi Saree,0.0,0,4099,72.0,"""₹1,147.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,AAR███LIF███YLE█████████LIM██████,"[{""size"":""Onesize""}]",NaN,"B-4███,40███402█████████36,███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
313,21421918,Baggit,Textured Handheld Bag,4.6,18,1890,46.0,"""₹1,039.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""M""}]","[""rw-21421918_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags

In [82]:
# no of rows and columns in the data set
df.shape

(1000, 24)

In [83]:
#structural summary of the data 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [84]:
#statistical summary of the data 
# mean,mediam,standard deviation,min,max and Quartiles
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [85]:
#categorical columns summary
# top frequent values, unique values and also counts 
df.describe(include='object')

,title,product_description,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,427,699,1000,219,699,438,1000,1000,1000
unique,454,989,466,1,1000,16,998,658,967,808,302,301,672,219,298,22,468,159,97
top,Roadster,Women Pink Solid Top,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""A pair of navy blue running sp...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Blouse"",""specification...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops
freq,30,3,25,1000,1,650,2,16,4,114,27,40,135,1,40,126,306,265,122

In [86]:
#columns from the dataset
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [87]:
#data type of each column from the dataset
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

Handling Missing Values

In [88]:
#handling missing values
#missing values in each column
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [89]:
'''
the columns having null values are discount,what_customers_said, 
seller_name,videos ,seller_information and variantions
%of missing values of discount =12.1%
%of missing values of what_customers_said= 57.3%
%of missing values of seller_name=30.1%
%of missing values of videos=78.1%
%of missing values of seller_infomation=30.1%
%of missing values of variations=56.2
 '''

#filling null data
#filling discount with median
df["discount"] = df["discount"].fillna(df["discount"].median())
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                    0
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [90]:
#seller_columns non null values
print(df["seller_name"].sample(10))

80                       Sup███om ███
153                Sle███ Ap███els███
117             Ape███ppa███s -██████
356                               NaN
491    HOU███OF ███NDS█████████LLP███
260          TRA███LA ███OM █████████
33           V S███ CR███ION█████████
321                               NaN
801                               NaN
742                               NaN
Name: seller_name, dtype: object

In [91]:
#handling missing value of seller_name
df["seller_name"] = df["seller_name"].fillna("Unknown Seller")
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                    0
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name                 0
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [92]:
#displaying seller_information column
print(df["seller_information"].sample(10))

496    C-1███ Ba███ent█████████Col███████████████████...
1                                                    NaN
210    9/1███, S███et █████████ula███████████████████...
347    10T███LOO███DU █████████ITY███████████████████...
37     BLD███NO.███BAS█████████VAI███████████████████...
828    Plo███o- ███ 1s█████████Sui███████████████████...
577    1 s███loo███Cab█████████-01███████████████████...
844                                                  NaN
316    Blo███B-1███abi█████████-24███████████████████...
856                                                  NaN
Name: seller_information, dtype: object

In [93]:
#handling missing values for seller_information
df["seller_information"] = df["seller_information"].fillna("Information not Found")
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                    0
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name                 0
sizes                       0
videos                    781
seller_information          0
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [94]:
#display sample data of what_customer_said column
print(df['what_customers_said'].dtype) #object

#example data 
print(df[df["what_customers_said"].notna()]["what_customers_said"])

object
23     [{"percentage":"100","value_name":"Fit, Just R...
42     [{"percentage":"100","value_name":"Fit, Just R...
46     [{"percentage":"40","value_name":"Fit, A Littl...
48     [{"percentage":"100","value_name":"Fit, Just R...
51     [{"percentage":"70","value_name":"Fit, Just Ri...
                             ...
966    [{"percentage":"96","value_name":"Fit, Just Ri...
968    [{"percentage":"100","value_name":"Fit, A Litt...
969    [{"percentage":"50","value_name":"Fit, Just Ri...
970    [{"percentage":"67","value_name":"Fit, Just Ri...
971    [{"percentage":"67","value_name":"Fit, Just Ri...
Name: what_customers_said, Length: 427, dtype: object

In [95]:
#despite having 50%+ null values as we cannot ignore the feedback from the customers as they are 
#core business logic 
#handling the null values by adding an indicator flag (feature engineering !!)

#creating a indicator column as has_customer_reviews
df["has_customer_reviews"]=df['what_customers_said'].notna().astype(int)

#filling the null values with an empty list to preserve sturcture
df["what_customers_said"] = df["what_customers_said"].fillna("[]")

# Verify
print(df["what_customers_said"].isnull().sum())

#view the result
df[['what_customers_said', 'has_customer_reviews']].sample(10)

0

                                   what_customers_said  has_customer_reviews
488                                                 []                     0
754  [{"percentage":"50","value_name":"Fit, Just Ri...                     1
101  [{"percentage":"50","value_name":"Fit, A Littl...                     1
956                                                 []                     0
713                                                 []                     0
529                                                 []                     0
321                                                 []                     0
621                                                 []                     0
351  [{"percentage":"60","value_name":"Fit, Just Ri...                     1
210                                                 []                     0

In [96]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                    0
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said         0
seller_name                 0
sizes                       0
videos                    781
seller_information          0
variations                562
best_offer                  0
more_offers                 0
category                    0
has_customer_reviews        0
dtype: int64

In [ ]:
#sample data of vide0s and variations column which are not null
print(df["videos"].sample(10))

879                                                  NaN
758    ["https://videos.myntassets.com/assets/videos/...
16                                                   NaN
274                                                  NaN
869                                                  NaN
551                                                  NaN
613    ["https://videos.myntassets.com/assets/videos/...
573    ["https://videos.myntassets.com/assets/videos/...
14                                                   NaN
382    ["rw-18973648_cae700","https://videos.myntasse...
Name: videos, dtype: object

In [105]:
#dropping videos column as doesnt effect the actual analysis of the data
df=df.drop(columns=["videos"])

#verification 
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'has_customer_reviews'],
      dtype='object')

In [109]:
#sample data of variations column
print(df["variations"].sample(10))

64     [{},{},{},{}]
987              NaN
678    [{},{},{},{}]
5            [{},{}]
538          [{},{}]
248             [{}]
705          [{},{}]
652              NaN
617              NaN
681              NaN
Name: variations, dtype: object

In [110]:
#dropping the variations column as there is no valid data
df=df.drop(columns=["variations"])

print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'best_offer',
       'more_offers', 'category', 'has_customer_reviews'],
      dtype='object')

Basic Operations